### ISSUE TITLE
New `strGlass` type "Whiskey Glass" breaks the tequila page and other cocktail pages that require that glass type.

### ISSUE THREAD

**Issue by ArelySkywalker** [ArelySkywalker/Six-Gummy-Bears-and-some-Scotch#17]
Add new 'whiskeyglass.png' icon under /src/Components/Images/glass/
![whiskeyglass](https://user-images.githubusercontent.com/11999676/108938609-69241180-761e-11eb-86b2-6edd21350f4c.png)

**Comment by eynglv** [comment]
Hey! Can I take this issue?

**Comment by ArelySkywalker** [comment]
@eynglv yes you can! 😊

**Comment by eynglv** [comment]
@ArelySkywalker submitted a PR!

**Comment by ArelySkywalker** [comment]
Change has been deployed! 

If you would like to add your username/name to the contributors list, you can edit the README file and add your name to the bottom of the list. :)

The format should be:
{ Name }, { Title }, { Favorite Drink }

Examples:
Arely Miramontes Rodríguez, Software Engineer, Margarita
Cersei Lannister, Queen of the Seven Kingdoms, Wine
Jane Doe, Student, Orange Juice
myUserName, Self Taught Student, Water
